In [1]:
import pandas as pd

In [2]:
countdf = pd.read_csv("/Users/maryallen/psea/testdata/value_expression_large.csv")

In [3]:
countdf

,Unnamed: 0,ENSG00000000003,ENSG00000000005,ENSG00000000419,ENSG00000000457,ENSG00000000460,ENSG00000000938,ENSG00000000971,ENSG00000001036,ENSG00000001084,...,ENSG00000285791,ENSG00000285794,ENSG00000285799,ENSG00000285868,ENSG00000285889,ENSG00000285950,ENSG00000285976,ENSG00000285978,ENSG00000285980,Patient
0,0,29.511994,0.0,677.093271,874.190945,150.077267,26334.455147,95.024351,578.658908,866.943007,...,10.252511,0.0,0.000000,1.998728,0.000000,0.000000,1370.464093,0.000000,0.0,Emogene
1,1,47.903916,0.0,879.069049,930.875180,183.951032,15682.507883,78.464111,537.852927,961.721812,...,1.562467,0.0,0.000000,3.718323,0.000000,0.000000,1259.587492,1.846324,0.0,Zahara
2,2,7.905217,0.0,488.503524,818.347118,74.005183,33615.530606,109.863489,851.952538,508.190126,...,0.000000,0.0,0.000000,3.069064,0.000000,0.000000,1050.229812,2.025464,0.0,Mariana
3,3,17.685953,0.0,929.965594,918.387410,193.038991,24488.634973,72.569624,650.918678,1109.326807,...,11.676310,0.0,0.940814,0.780242,0.000000,0.000000,1405.753895,0.000000,0.0,Hedy
4,4,11.323561,0.0,325.045816,724.708980,104.653678,36383.471139,47.641928,1073.361378,586.107596,...,3.024999,0.0,0.000000,1.937815,1.927311,0.000000,1126.137152,0.000000,0.0,Ernesta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,249,13.076811,0.0,411.902982,1019.786507,178.794343,37095.415078,139.781590,1808.847991,1075.848340,...,11.978000,0.0,0.000000,0.000000,0.000000,0.000000,2636.782273,1.188437,0.0,Mandi
250,250,24.520282,0.0,403.695955,801.196142,122.657871,32767.179262,127.010977,885.978494,690.735888,...,0.000000,0.0,0.000000,4.535087,0.000000,1.125288,1306.103548,0.000000,0.0,Shawn
251,251,17.245520,0.0,1031.857085,883.812585,167.355834,33240.011315,128.489847,997.965431,483.363160,...,6.404473,0.0,0.000000,2.262085,0.000000,0.000000,1803.369739,0.000000,0.0,Lotti
252,252,36.334698,0.0,729.616718,955.090153,190.333714,28292.970464,70.969152,864.603711,721.255142,...,23.862106,0.0,0.000000,0.000000,0.000000,0.000000,1580.287711,0.000000,0.0,Rennie
253,253,30.230726,0.0,832.120160,939.566482,125.426379,27286.655916,131.816722,510.059411,775.502847,...,4.279670,0.0,0.000000,0.000000,0.000000,0.000000,1501.936427,1.023802,0.0,Karon

In [4]:
genedf = pd.read_csv("/Users/maryallen/psea/testdata/genes.csv")
genedf

,Unnamed: 0,seqnames,start,end,width,strand,source,type,gene_id,gene_version,gene_name,gene_source,gene_biotype
0,1,1,11869,14409,2541,+,havana,gene,ENSG00000223972,5,DDX11L1,havana,transcribed_unprocessed_pseudogene
1,2,1,14404,29570,15167,-,havana,gene,ENSG00000227232,5,WASH7P,havana,unprocessed_pseudogene
2,3,1,17369,17436,68,-,mirbase,gene,ENSG00000278267,1,MIR6859-1,mirbase,miRNA
3,4,1,29554,31109,1556,+,havana,gene,ENSG00000243485,5,MIR1302-2HG,havana,lincRNA
4,5,1,30366,30503,138,+,mirbase,gene,ENSG00000284332,1,MIR1302-2,mirbase,miRNA
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58730,58731,KI270711.1,4612,29626,25015,-,ensembl,gene,ENSG00000271254,6,AC240274.1,ensembl,protein_coding
58731,58732,KI270713.1,21861,22024,164,-,ensembl,gene,ENSG00000275405,1,RF00003,ensembl,snRNA
58732,58733,KI270713.1,30437,30580,144,-,ensembl,gene,ENSG00000275987,1,RF00003,ensembl,snRNA
58733,58734,KI270713.1,31698,32528,831,-,ensembl,gene,ENSG00000277475,1,AC213203.2,ensembl,protein_coding
58734,58735,KI270713.1,35407,35916,510,+,ensembl,gene,ENSG00000268674,2,AC213203.1,ensembl,protein_coding

In [5]:
chronlyfiles = ["21", "22", "13", "18"]
for chronly in chronlyfiles:
    genedf_chr22 = genedf[genedf["seqnames"]==chronly]
    genedf_chr22 = genedf_chr22[genedf_chr22["gene_id"].isin(countdf.columns)]
    keepnames = ["Patient"]+genedf_chr22["gene_id"].to_list()
    countdf_22 = countdf[keepnames]
    countdf_22.to_csv("/Users/maryallen/psea/testdata/value_expression_chr"+chronly+".csv")